import {APP_API_URL_LOCAL, APP_API_URL,  APP_AUTH_APIKEY,  APP_AUTH_AUTHDOMAIN,  APP_AUTH_DATABASEURL,
    APP_AUTH_PROJECTID,  APP_AUTH_STORAGEBUCKET,  APP_AUTH_MESSAGINGSENDERID , APP_AUTH_APPID, 
    APP_AUTH_MEASUREMENTID, IOS_CLIENT_ID, ANDROID_CLIENT_ID} from '@env'

    const devEnvirement : any = {
        APP_API_URL_LOCAL, APP_API_URL,  APP_AUTH_APIKEY,  APP_AUTH_AUTHDOMAIN,  APP_AUTH_DATABASEURL,
        APP_AUTH_PROJECTID,  APP_AUTH_STORAGEBUCKET,  APP_AUTH_MESSAGINGSENDERID , APP_AUTH_APPID, 
        APP_AUTH_MEASUREMENTID, IOS_CLIENT_ID, ANDROID_CLIENT_ID
    };

    const prodEnviroment: any = {
        APP_API_URL_LOCAL, APP_API_URL,  APP_AUTH_APIKEY,  APP_AUTH_AUTHDOMAIN,  APP_AUTH_DATABASEURL,
        APP_AUTH_PROJECTID,  APP_AUTH_STORAGEBUCKET,  APP_AUTH_MESSAGINGSENDERID , APP_AUTH_APPID, 
        APP_AUTH_MEASUREMENTID, IOS_CLIENT_ID, ANDROID_CLIENT_ID
    };

  //  export default __DEV__ ? devEnvirement : prodEnviroment;

  export default devEnvirement;